### PR TITLE
feat: added the ability to process server actions

### PR DESCRIPTION
**Pull request by eriktisme**
Fixes #

### CODE REVIEW

**Comment by eriktisme** [comment]
This PR for sure needs fine tunning, it should only send through the non-GET requests to the server actions.

**Comment by eriktisme** [comment]
@matusfaro I can work on this PR if that is inline with the contributions guidelines.

**Comment by eriktisme** [comment]
@matusfaro if you have time to check it out that be great, if not, I'll plan something in my calendar to spend time on it.

**Comment by matusfaro** [comment]
@eriktisme Hi, it looks good, just take it out of draft when you're finished with it and i'll merge it and release a new version.

**Comment by eriktisme** [comment]
@matusfaro I cannot do anything locally for some reason it won't install any of the packages. I'm on a Macbook Pro with an M1 chip

**Comment by matusfaro** [comment]
> @matusfaro I cannot do anything locally for some reason it won't install any of the packages. I'm on a Macbook Pro with an M1 chip

I'm on an M2 so that shouldn't be the problem.

This project uses "projen", to get started, run the following command `yarn projen`. It will set everything up initially.

**Pull request closed without merging**
